### ISSUE TITLE
precompile error no clue why

### ISSUE THREAD

**Issue by edegraaff** [RoelKroes/HorusBinary_Tracker#3]
Hi, i am trying to build the project. 
I have no clue what could cause this, i did fill all settings in the settings.h
Could it be the arduino should be connected? 

\HorusBinary_Tracker-main\ADC\FSK4_Mod.ino:12:20: error: 'PhysicalLayer' was not declared in this scope
 int16_t fsk4_setup(PhysicalLayer* phy, float base, uint32_t shift, uint16_t rate){
                    ^~~~~~~~~~~~~

\horusBinary_Tracker-main\ADC\FSK4_Mod.ino:12:35: error: 'phy' was not declared in this scope
 int16_t fsk4_setup(PhysicalLayer* phy, float base, uint32_t shift, uint16_t rate){

Hum, maybe found the reason .... if no arduino connected the IDE want to assign ip ... 
![image](https://user-images.githubusercontent.com/12442749/211655043-41c21d9f-f177-45f9-bcaf-ad48ea8ce2e5.png)

Connected pro mini
![image](https://user-images.githubusercontent.com/12442749/211656748-85c9c5f6-b161-411a-858f-6df3c0a110f9.png)

Darn error stays, does someone have any clue what could cause this error?

**Comment by RoelKroes** [comment]
The source compiles without errors here in IDE v2.0.3.
Be sure to have all files in the same folder. 
Use the latest version of the radiolib library.

**Comment by edegraaff** [comment]
> The source compiles without errors here in IDE v2.0.3. Be sure to have all files in the same folder. Use the latest version of the radiolib library.
I am completely puzzeled, i downloaded again the zip, unpacked it, and tried to compile, same error.
The i tried to compile it in the old ide that also still on the pc same error
Then i transported the files to my home folder same error

All the other projects did compile and transferred without problems but i will try to use another arduino project to test
Compiled the tbtracker project, on the old ide, compilation no issues worked fine 
Compiled the tbtracher project on de new ide 2.03 no issues worked fine 
I will compile on an old notebook, to see if it is hardware related, is an pentium silver. 
On the another notebook same problem same error... notebook is running 2.03

Board is pro or pro mini .. right?  
All files are in the same folder, i even tryed to place them in both folders...  

Idea to pack, your program folder and the lib folder as a zip and swap them and new test? 

This is a real strange error..

Google delivers me hits on the pin declarations for boards that don;t have them, for what model arduino did you compile the code at your machine? Maybe there is the clue somewhere... 

Will dig a bit deeper. 

Hum what version of radiolib do you use, the fsk4_tone function demands the fysicallayer maibe the function is a bit changed?

**Comment by edegraaff** [comment]
Problem is IDE on 2 notebooks that have some sort of artefact in them. The third notebook has never seen the IDE and installation of the ide without a yes on the suggested drivers delivered a precompile without issues. 

next step clean up the mess on the daybydat notebook.
