### ISSUE TITLE
Baudrate set to 100 but transmission is 50 baud

### ISSUE THREAD

**Issue by zanco** [RoelKroes/HorusBinary_Tracker#5]
Hi,
Running your horusbinary tbtracker on a 8 MHz 328p

Againgst the advice I did set the baudrate to 100 baud, for being compatible with general receiver settings, but the tracker transmits at 50 baud.

Any suggestions ?

Thanks

(horus V2 enabled)

**Comment by zanco** [comment]
#define BITDURATION_DELAY 310

With this setting and baudrate set at 100 baud the tracker transmits 100 baud on an 8 MHz at328p

**Comment by RoelKroes** [comment]
Well done for getting it to work at 100 baud on a 8 MHz processor :-)
I hope the frequency will be stable.

Don't forget to set Tone Spacing in the Horus GUI to 244 instead of the standard 270.  270 will probably work quite well, but 244 is the exact number to use.
