### ISSUE TITLE
Compatibility with anything else than the Arduino

### ISSUE THREAD

**Issue by Mika-1818** [RoelKroes/HorusBinary_Tracker#6]
As my Arduino Nanos memory is too small, I tried using an ESP32 which doesn't work.
The library util/crc16.h isn't compatible with anything else than the Arduino.
Maybe someone can find a workaround. 
73

Mika, DL8MIK

**Comment by RoelKroes** [comment]
Hi Mika,

You should be able to get it to work, if you use older versions of the libraries. For example Radiolib v5.5.

But a better solution would be to use an esp32 with this repository: https://github.com/RoelKroes/TBTracker-ESP32
This repo supports Horus_Binary V1, V2, LoRa, RTTY, LoRa-APRS. So you can use even more protocols.

73,

Roel (PD7R).

**Comment by Mika-1818** [comment]
Thanks for your quick answer! Will look into that.
